name: firebase_explorer
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  image_picker: ^1.0.7
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.firebase_explorer
    iosBundleIdentifier: com.example.firebaseExplorer
